spring.application.name=sks-springboot-demo
spring.datasource.url=jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:demo}
spring.datasource.username=${DB_USER:demo}
spring.datasource.password=${DB_PASSWORD:demo-postgres-password}
spring.datasource.hikari.initialization-fail-timeout=-1
spring.datasource.hikari.connection-timeout=5000
demo.nacos.server=${NACOS_SERVER:nacos:8848}
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=20s
